version: "1.1"
spec:
  servicePort: 80
  hostname: ""
  sharedDir:
    path: /var/www/html
    storage: '2Gi'
  podTemplate:
    containers:
      - name: php
        image: 'devpanel/php-fpm:7.4'
        env:
          - name: "APP_ROOT"
            value: "/var/www/html"
        ports:
          - containerPort: 9000
            name: fastcgi
      - name: nginx
        image: 'wodby/nginx:latest'
        env:
          - name: NGINX_SERVER_ROOT
            value: "/var/www/html/"
          - name: "NGINX_VHOST_PRESET"
            value: "drupal7"
          - name: NGINX_BACKEND_HOST
            value: '0.0.0.0'
        ports:
          - containerPort: 80
            name: http
          - containerPort: 443
            name: https